FROM node:22-alpine

WORKDIR /app


COPY package.json package-lock.json* ./
#--legacy-peer-deps is couse of versions conflict
RUN npm install --legacy-peer-deps 


COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]