export {
  createListItemId,
  createParagraph,
  createListItem,
  createBulletedList,
  createDefaultNoteContent,
  cloneBlocks,
} from '@/utils/noteContentCreate'

export {
  coerceNoteBlocksFromJson,
  isParagraph,
  isBulletedList,
  normalizeBlocksForApi,
  spansToPlainText,
  plainTextToSpans,
  ensureNonEmptySpans,
  splitSpansAtOffset,
  mergeSpans,
  isEffectivelyEmpty,
  blockToPlainText,
  isBlockBold,
  toggleBlockBold,
  setBlockSize,
  getBlockSize,
  blockSizeClass,
  blocksSnapshotEqual,
  extractPreviewText,
  noteBlocksToPlainParagraphs,
} from '@/utils/noteContentNormalize'
